# Generated by Django 5.0.4 on 2024-06-28 01:05

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=200, verbose_name='descricao')),
                ('tipo_centro_custo', models.CharField(choices=[('Centro de custo/lucro pai', 'Centro de custo/lucro pai'), ('Centro de custo/lucro filho', 'Centro de custo/lucro filho')], max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Poupança', 'Poupança')], max_length=20)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('gerente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('apelido_conta', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_conta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_chave_pix', models.CharField(choices=[('CPF/CNPJ', 'CPF/CNPJ'), ('E-mail', 'E-mail'), ('Telefone', 'Telefone'), ('Aleatória', 'Aleatória')], max_length=20)),
                ('chave_pix', models.CharField(max_length=100)),
                ('situacao_conta', models.CharField(max_length=100)),
                ('agrupamento', models.CharField(max_length=100)),
                ('permite_lancamentos', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome fantasia')),
                ('razao_social', models.CharField(max_length=100, verbose_name='razao social')),
                ('cnpj_cpf', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('insc_estadual', models.CharField(blank=True, max_length=18, null=True, verbose_name='I.E.')),
                ('insc_municipal', models.CharField(blank=True, max_length=18, null=True, verbose_name='I.M.')),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('site_empresa', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('setor_empresa', models.CharField(max_length=100)),
                ('ramo_atuacao', models.CharField(max_length=100)),
                ('produtos_servicos', models.TextField()),
                ('numero_empregados', models.IntegerField()),
                ('data_criacao', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Minha empresa',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=200, verbose_name='descricao')),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='tags')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', colorfield.fields.ColorField(auto_created=True, default='#FFFFFF', image_field=None, max_length=7, samples=None)),
                ('descricao', models.CharField(default='', max_length=200, verbose_name='descricao')),
                ('ativo', models.BooleanField(default=True)),
                ('is_categoria_filha', models.BooleanField(default=False, verbose_name='Categoria filha')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, unique=True)),
                ('classificacao', models.CharField(choices=[('MI', 'Mista'), ('DE', 'Despesa'), ('RE', 'Receita')], default='MI', max_length=3)),
                ('data_criada', models.DateTimeField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.categoria', verbose_name='Categoria pai')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
