# Generated by Django 5.0.4 on 2025-01-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='situacao_conta',
            field=models.BooleanField(default=True),
        ),
    ]
