# Generated by Django 5.0.4 on 2025-01-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0002_alter_conta_situacao_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='situacao_conta',
            new_name='ativo',
        ),
    ]
