# Generated by Django 5.0.4 on 2024-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0004_remove_category_type_category_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.CharField(choices=[('MISTA', 'Mista'), ('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], default='MI', max_length=7),
        ),
    ]
