# Generated by Django 5.0.4 on 2024-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0008_remove_choice_question_categoria_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
