# Generated by Django 5.0.4 on 2024-04-11 17:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0009_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='#225e39', image_field=None, max_length=25, samples=None),
        ),
    ]
