# Generated by Django 5.0.4 on 2024-04-11 18:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0010_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(auto_created=True, default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
