# Generated by Django 5.0.4 on 2024-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0012_categoria_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_categoria_filha',
            field=models.BooleanField(default=False),
        ),
    ]
