# Generated by Django 5.0.4 on 2024-04-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0014_alter_categoria_categoria_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.categoria', verbose_name='Categoria pai'),
        ),
    ]
