# Generated by Django 5.0.4 on 2024-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0015_alter_categoria_categoria_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='is_categoria_filha',
            field=models.BooleanField(default=False, verbose_name='Categoria filha'),
        ),
    ]
