# Generated by Django 5.0.4 on 2024-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0016_alter_categoria_is_categoria_filha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='descricao'),
        ),
    ]
