# Generated by Django 5.0.4 on 2024-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0017_remove_categoria_nome_categoria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Poupança', 'Poupança')], max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Poupança', 'Poupança')], max_length=20)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('gerente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('apelido_conta', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('saldo_conta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_chave_pix', models.CharField(choices=[('CPF/CNPJ', 'CPF/CNPJ'), ('E-mail', 'E-mail'), ('Telefone', 'Telefone'), ('Aleatória', 'Aleatória')], max_length=20)),
                ('chave_pix', models.CharField(max_length=100)),
                ('situacao_conta', models.CharField(max_length=100)),
                ('agrupamento', models.CharField(max_length=100)),
                ('permite_lancamentos', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome fantasia')),
                ('razao_social', models.CharField(max_length=100, verbose_name='razao social')),
                ('cnpj_cpf', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('insc_estadual', models.CharField(blank=True, max_length=18, null=True, verbose_name='I.E.')),
                ('insc_municipal', models.CharField(blank=True, max_length=18, null=True, verbose_name='I.M.')),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('site_empresa', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('setor_empresa', models.CharField(max_length=100)),
                ('ramo_atuacao', models.CharField(max_length=100)),
                ('produtos_servicos', models.TextField()),
                ('numero_empregados', models.IntegerField()),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
