# Generated by Django 5.0.4 on 2024-04-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0018_cadconta_cadempresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadConta',
            new_name='Conta',
        ),
        migrations.RenameModel(
            old_name='CadEmpresa',
            new_name='Empresa',
        ),
    ]
