# Generated by Django 5.0.4 on 2024-06-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('finan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('competencia', models.DateField(blank=True, null=True, verbose_name='Competência')),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Documento')),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=20, verbose_name='Tipo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(choices=[('PAGO', 'Pago'), ('APAGAR', 'À Pagar')], default='PAGO', max_length=20, verbose_name='Situação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.conta', verbose_name='Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('apropriacao_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finan.categoria', verbose_name='Categoria')),
                ('centro_custo_lucro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finan.centrocusto', verbose_name='Centro custo/lucro')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forma_pagamento', to='finan.formapagamento', verbose_name='Lançamento')),
                ('fornecedor_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_cliente', to='cadastros.fornecedorcliente', verbose_name='Fornecedor/Cliente')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fluxo.lancamento', verbose_name='Lançamento')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='fluxo.lancamento', verbose_name='Lançamento')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tranferencia', models.DateField(verbose_name='Data da Transferência')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='finan.conta', verbose_name='Conta destino')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_origem', to='finan.conta', verbose_name='Conta origem')),
            ],
        ),
    ]
