# Generated by Django 5.0.4 on 2025-01-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finan', '0001_initial'),
        ('fluxo', '0002_rename_data_tranferencia_transferencia_data_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forma_pagamento', to='finan.formapagamento', verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='situacao',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('APAGAR', 'a Pagar')], default='PAGO', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='finan.conta', verbose_name='Conta destino'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='finan.conta', verbose_name='Conta origem'),
        ),
    ]
